### ISSUE TITLE
Need a project idea

### ISSUE THREAD

**Issue by CarpenterT** [CarpenterT/Cen3031GroupProject#1]
We need a project idea and a description.

**Comment by CarpenterT** [comment]
I've got an idea for a project where we create a web app that lets users create and manage groups for projects/meetings. I was mainly inspired by how someone had to go and create a Discord and Slack server just so that those of us taking this class could form groups. It would be useful to have a tool that even teachers could use to let their students group up -- particularly since Canvas's system is so crap.
I think the flow of the program would go like this:
- A professor wants to let their students create their own groups for project (like we had to for this class).
- They use our web app, creating a general server that contains all of the students. Imagine it somewhat like a Slack server.
- Students can be automatically assigned to a group or be allowed to join whichever they like.
- In the latter case, the prof can create a general template for students looking for a group, or students can create their own (like we did when looking for a group in the discord server for this class). Name, email, preferences, experience, etc.
- The app would also let students in a group have their own private workspace for direct messages, group chats, etc. We could implement zoom's API for creating meetings (I have no idea if Zoom lets users do that), so that they could arrange meetings over Zoom. We could probably have some sort of map functionality that lets users pick a location and get an address for where they want to meet up (I think Angular Material has a map function we could use, though I don't know if you can extract addresses). etc, etc.

I think this would be a decent idea since its a helpful, relatively simple tool, it's web based, it can use a server on the backend, and most importantly, we can get a basic functionality and then just add useful features/increase scope over the course of the Sprints.
Let me know what you guys think.

**Comment by drosabal** [comment]
That idea seems pretty solid to me. Simple enough to implement the basics and then add extra functionality over time as needed.
